# Generated by Django 4.1 on 2022-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=1000, null=True)),
                ('codigo', models.PositiveIntegerField(null=True)),
                ('quantidadeInicial', models.PositiveIntegerField(null=True)),
                ('unidadeMedida', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
